<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "loginredirect"
 *
 * Auto generated by Extension Builder 2016-01-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Login redirect',
	'description' => 'Redirect to external url when a user with given usergroup is logged in',
	'category' => 'plugin',
	'author' => 'HOJA.M.A',
	'author_email' => 'hoja.ma@tnt-graphics.ch',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '2.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-9.0.00',
		),
		'conflicts' => array(
		), 
		'suggests' => array(
		),
	),
);